        SUBROUTINE INITIALIZE(COMPUTE)
        save
c
        INCLUDE 'parameters.include'
c
        INTEGER I, LOOP_NUM(N_VARIABLES), LOOP_COUNT(N_VARIABLES)
C
        LOGICAL OPEN, STEP_VARIABLE(N_VARIABLES)
        LOGICAL STEP_THIS_TIME(N_VARIABLES)
        LOGICAL CALL_SUB(N_CALLS,N_SUB_CALLS)
        LOGICAL COMPUTE
C
        COMMON /I_COUNT/ LOOP_NUM, LOOP_COUNT
        COMMON /L_FLAGS/ STEP_VARIABLE, STEP_THIS_TIME, CALL_SUB, OPEN
c
        OPEN = .FALSE.
        COMPUTE = .TRUE.
C
        DO 10 I=1,N_VARIABLES
            LOOP_COUNT(I) = 1
            STEP_VARIABLE(I) = .FALSE.
            STEP_THIS_TIME(I) = .FALSE.
10      CONTINUE
C
        RETURN
        END
